apiVersion: v1
kind: Service
metadata:
  name: mylb
spec:
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  #clusterIP: 10.0.171.239
  type: LoadBalancer
#status:
  #loadBalancer:
    #ingress:
    #- ip: 192.0.2.127
